<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Round Neck T-Shirt',
                'slug' => 'round-neck-t-shirt',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 27.00,
                'discount_price' => 22.00,
                'color' => '#e8c2ff,#9cfdd5',
                'size' => 'S,M,XL',
                'image' => 'backend/images/products/1771326806_6_1.jpg,backend/images/products/1771326806_6_2.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Cloth',
            ],
            [
                'id' => 2,
                'category_id' => 3,
                'name' => 'Full Sleeve Shirt',
                'slug' => 'full-sleeve-shirt',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 12.00,
                'discount_price' => 10.00,
                'color' => '#01f1f1,#b89df8',
                'size' => 'S,M,XL',
                'image' => 'backend/images/products/1771326849_7_1.jpg,backend/images/products/1771326849_7_2.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Cloth',
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'name' => 'Cute Baby Toy',
                'slug' => 'cute-baby-toy',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 40.00,
                'discount_price' => 30.00,
                'color' => '#90cdf7,#ff3b66,#ffc476,#1af0ba',
                'size' => 'S,M',
                'image' => 'backend/images/products/1771326927_1_1.jpg,backend/images/products/1771326927_1_2.jpg,backend/images/products/1771326927_1_3.jpg,backend/images/products/1771326927_1_4.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Watch',
            ],
            [
                'id' => 4,
                'category_id' => 2,
                'name' => 'Jumbo Carry Bag',
                'slug' => 'jumbo-carry-bag',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 50.00,
                'discount_price' => 40.00,
                'color' => '#fdbf04',
                'size' => 'M',
                'image' => 'backend/images/products/1771326969_2_2.jpg,backend/images/products/1771326969_2_3.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Bag',
            ],
            [
                'id' => 5,
                'category_id' => 2,
                'name' => 'Designer Leather Purses',
                'slug' => 'designer-leather-purses',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 40.00,
                'discount_price' => 30.00,
                'color' => '#75e3ff,#11f7d8,#acff7c,#e996fa',
                'size' => 'S',
                'image' => 'backend/images/products/1771327028_3_1.jpg,backend/images/products/1771327028_3_2.jpg,backend/images/products/1771327028_3_4.jpg,backend/images/products/1771327028_3_5.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Bag',
            ],
            [
                'id' => 6,
                'category_id' => 2,
                'name' => 'Leather Belt for Men',
                'slug' => 'leather-belt-for-men',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 15.00,
                'discount_price' => 10.00,
                'color' => '#9e9e9e,#eb8e76',
                'size' => 'M,XL',
                'image' => 'backend/images/products/1771327095_5_1.jpg,backend/images/products/1771327095_5_2.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Bag',
            ],
            [
                'id' => 7,
                'category_id' => 4,
                'name' => 'Digital Smart Watches',
                'slug' => 'digital-smart-watches',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 100.00,
                'discount_price' => 80.00,
                'color' => '#e9dddd,#ffd5cb,#92e4fd',
                'size' => 'M',
                'image' => 'backend/images/products/1771327120_8_1.jpg,backend/images/products/1771327120_8_2.jpg,backend/images/products/1771327120_8_3.jpg,backend/images/products/1771327120_8_4.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Bag',
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'name' => 'Canvas Cowboy Hat',
                'slug' => 'canvas-cowboy-hat',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 12.00,
                'discount_price' => 10.00,
                'color' => '#ebbf60,#b4fc57,#2ea1cd',
                'size' => 'XL',
                'image' => 'backend/images/products/1771327144_4_1.jpg,backend/images/products/1771327144_4_2.jpg,backend/images/products/1771327144_4_3.jpg,backend/images/products/1771327144_4_4.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Bag',
            ],
            [
                'id' => 9,
                'category_id' => 5,
                'name' => 'Smart Phone',
                'slug' =>'smart-phone',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley.',
                'base_price' => 100.00,
                'discount_price' => 80.00,
                'color' => '#f7f7f7,#f7f7f7',
                'size' => 'S,M,L',
                'image' => 'backend/images/products/1771327164_42_1.jpg,backend/images/products/1771327164_42_2.jpg',
                'stock' => 10,
                'status' => 1,
                'tag' => 'Bag',
            ],
        ]);
    }
}
